recipes.addShaped(<exnihilocreatio:block_sieve>, [[<minecraft:log:*>, null, <minecraft:log:*>],[<minecraft:log:*>, <extrautils2:compresseddirt>, <minecraft:log:*>], [<minecraft:sapling:*>, null, <minecraft:sapling:*>]]);
recipes.addShapeless(<exnihilocreatio:item_material:1>, [<minecraft:clay_ball>,<minecraft:quartz>,<minecraft:quartz>]);
recipes.addShaped(<exnihilocreatio:item_mesh:4>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>],[<minecraft:diamond>, <exnihilocreatio:item_mesh:3>, <minecraft:diamond>], [<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>]]);
recipes.addShaped(<exnihilocreatio:item_mesh:3>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <exnihilocreatio:item_mesh:2>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<exnihilocreatio:item_mesh:2>, [[<minecraft:flint>, <minecraft:flint>, <minecraft:flint>],[<minecraft:flint>, <exnihilocreatio:item_mesh:1>, <minecraft:flint>], [<minecraft:flint>, <minecraft:flint>, <minecraft:flint>]]);
recipes.addShaped(<exnihilocreatio:crook_stone>, [[<minecraft:cobblestone:*>, <minecraft:cobblestone:*>, null],[null, <minecraft:cobblestone:*>, null], [null, <minecraft:cobblestone:*>, null]]);
recipes.addShaped(<exnihilocreatio:block_barrel0>, [[<minecraft:log:*>, null, <minecraft:log:*>],[<minecraft:log:*>, null, <minecraft:log:*>], [<minecraft:log:*>, <minecraft:log:*>, <minecraft:log:*>]]);
recipes.addShaped(<exnihilocreatio:hammer_stone>, [[null, <extrautils2:compressedcobblestone>, null],[null, <minecraft:stick>, <extrautils2:compressedcobblestone>], [<minecraft:stick>, null, null]]);
recipes.addShaped(<exnihilocreatio:hammer_wood>, [[null, <minecraft:log:*>, null],[null, <minecraft:stick>, <minecraft:log:*>], [<minecraft:stick>, null, null]]);
